language: c++
sudo: required


addons:
  apt:
    packages:
      - g++-6
    sources: &sources
      - ubuntu-toolchain-r-test

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0/install

matrix:
  include:
    - env: BUILD_TYPE=Debug
      os: osx
      osx_image: xcode8
      compiler: clang
    - env: GCC_VERSION=6 BUILD_TYPE=Debug COMPILER=g++-6
      os: linux
      dist: trusty
      compiler: gcc

#install:
#  - if [[ -n "$CLANG_VERSION" ]]; then export CXX=clang++-$CLANG_VERSION CC=clang-$CLANG_VERSION; fi
#  - if [[ -n "$GCC_VERSION" ]]; then export CXX=g++-$GCC_VERSION CC=gcc-$GCC_VERSION; fi
#  - JOBS=2
#  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
#  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"


#before_script:
#  - cd "${TRAVIS_BUILD_DIR}"
#  - cmake . -Bbuild -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" -DCMAKE_BUILD_TYPE=$BUILD_TYPE
#  - cmake --build build -- -j$JOBS

before_install:
   - sh ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}.before_install.sh

install:
  - if [[ -n "$CLANG_VERSION" ]]; then export CXX=clang++-$CLANG_VERSION CC=clang-$CLANG_VERSION; fi
  - if [[ -n "$GCC_VERSION" ]]; then export CXX=g++-$GCC_VERSION CC=gcc-$GCC_VERSION; fi
  - JOBS=2
  - sh ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}.install.sh

before_script:
   - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then source /opt/qt56/bin/qt56-env.sh; fi
   - mkdir build && cd build

script:
    - sh ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}.script.sh
    - make -j4

#Build steps
#script:
#  - mkdir build
#  - cd build
#  - cmake .. && make
